# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login import *
from reg import *


class Ui_home_window(object):
    def OpenLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.window)
        self.window.show()

    def OpenRegistrations(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, home_window):
        home_window.setObjectName("home_window")
        home_window.resize(888, 662)
        home_window.setStyleSheet("background-color:rgb(252, 217, 255)")
        self.centralwidget = QtWidgets.QWidget(home_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(85, 170, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 70, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(170, 170, 255)")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 240, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 350, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 610, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        home_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(home_window)
        self.statusbar.setObjectName("statusbar")
        home_window.setStatusBar(self.statusbar)

        self.retranslateUi(home_window)
        QtCore.QMetaObject.connectSlotsByName(home_window)

        self.pushButton_2.clicked.connect(lambda: self.OpenRegistrations())
        self.pushButton_2.clicked.connect(home_window.close)

        self.pushButton.clicked.connect(lambda: self.OpenLogin())
        self.pushButton.clicked.connect(home_window.close)


    def retranslateUi(self, home_window):
        _translate = QtCore.QCoreApplication.translate
        home_window.setWindowTitle(_translate("home_window", "MainWindow"))
        self.label.setText(_translate("home_window", "Welcome to ANSZ Movie Ticketing System"))
        self.label_2.setText(_translate("home_window", "Handle your purchase in digital way"))
        self.pushButton.setText(_translate("home_window", "LOGIN TO YOUR ACCOUNT"))
        self.pushButton_2.setText(_translate("home_window", "REGISTRATION"))
        self.label_3.setText(_translate("home_window", "ANSZ, ALL Rights Reserved"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_window = QtWidgets.QMainWindow()
    ui = Ui_home_window()
    ui.setupUi(home_window)
    home_window.show()
    sys.exit(app.exec_())
