# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from admin_dashboard import *
from reg import *
from PyQt5.QtWidgets import QMessageBox
import sqlite3
from user_dashboard import *


class Ui_Login(object):
    def OpenRegistrations(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def OpenAdminDashboard(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_admin_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def OpenUserDashboard(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_user_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(280, 240, 291, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(280, 310, 291, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 250, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 320, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 140, 511, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(280, 370, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.go_toReg = QtWidgets.QPushButton(self.centralwidget)
        self.go_toReg.setGeometry(QtCore.QRect(410, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.go_toReg.setFont(font)
        self.go_toReg.setObjectName("go_toReg")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.go_toReg.clicked.connect(lambda: self.OpenRegistrations())
        self.go_toReg.clicked.connect(Login.close)
        self.login_button.clicked.connect(lambda: self.logintoSystem())

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Username"))
        self.label_2.setText(_translate("Login", "Password"))
        self.label_3.setText(_translate("Login", "LOGIN TO YOUR ACCOUNT"))
        self.login_button.setText(_translate("Login", "Login"))
        self.go_toReg.setText(_translate("Login", "Go to Registration"))

    def logintoSystem(self):
        conn = sqlite3.connect('movie_system.db')
        c = conn.cursor()
        uname = str(self.textEdit.toPlainText())
        password = str(self.textEdit_2.toPlainText())
        query = f"SELECT * from User_List Where Username='{uname}' AND Password='{password}';"
        c.execute(query)
        if uname == "" or password == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Please Provide Username and Password!!")
            msg.setWindowTitle("Error")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        elif uname == "admin" and password == "123":
            self.OpenAdminDashboard()
            Login.hide()
        elif not c.fetchone():
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Wrong Username or Password!!")
            msg.setWindowTitle("Error")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        else:
            y = uname
            self.window = QtWidgets.QMainWindow()
            self.message = y
            self.ui = Ui_user_window(y)
            self.ui.setupUi(self.window)
            self.window.show()
            Login.hide()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
