# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from login import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3

conn = sqlite3.connect('movie_system.db')
c = conn.cursor()


class Ui_MainWindow(object):
    def __init__(self):
        self.window = None
        self.ui = None

    def OpenLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 774)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(450, 130, 241, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 140, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(450, 200, 241, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(450, 270, 241, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 280, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(450, 340, 241, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 350, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 60, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(450, 410, 241, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(450, 480, 241, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(450, 550, 241, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 420, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 490, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 560, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 610, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 610, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(lambda: self.reg_button_click())
        # self.pushButton_2.clicked.connect(lambda: self.OpenLogin())
        # self.pushButton_2.clicked.connect(MainWindow.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Confrim Password"))
        self.label_5.setText(_translate("MainWindow", "Registration"))
        self.label_6.setText(_translate("MainWindow", "Initial Deposit"))
        self.label_7.setText(_translate("MainWindow", "Card Number"))
        self.label_8.setText(_translate("MainWindow", "CVV"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))

    def reg_button_click(self):
        username = str(self.textEdit.toPlainText())
        email = str(self.textEdit_2.toPlainText())
        password = str(self.textEdit_3.toPlainText())
        i_deposit = str(self.textEdit_5.toPlainText())
        if username == "" or email == "" or password == "" or i_deposit == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Please Make Sure All the Fields are Full!!")
            msg.setWindowTitle("Error!!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        else:
            c.execute(f"INSERT into User_List values ('{username}','{email}','{password}','{i_deposit}')")
            conn.commit()
            conn.close()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Registration Successfully Done!!")
            msg.setWindowTitle("Add")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
            self.pushButton_2.clicked.connect(lambda: self.OpenLogin())


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Registration_User = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Registration_User)
    Registration_User.show()
    sys.exit(app.exec_())
