# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox

conn = sqlite3.connect('movie_system.db')
c = conn.cursor()


class Ui_mng_window(object):
    def __init__(self, message):
        self.message = message
        query = f"Select * from user_list where username='{message}';"
        c.execute(query)
        x = c.fetchone()
        self.bal = x[3]
        self.mail = x[1]
        self.passw = x[2]
        self.uname = x[0]

    def setupUi(self, mng_window):
        mng_window.setObjectName("mng_window")
        mng_window.resize(1120, 718)
        mng_window.setStyleSheet("background-color:rgb(181, 255, 187)")
        self.centralwidget = QtWidgets.QWidget(mng_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 230, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(770, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(770, 340, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(770, 210, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 230, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 290, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(700, 350, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 400, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 610, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setObjectName("label_9")
        mng_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mng_window)
        self.statusbar.setObjectName("statusbar")
        mng_window.setStatusBar(self.statusbar)

        self.retranslateUi(mng_window)
        QtCore.QMetaObject.connectSlotsByName(mng_window)
        self.load_data()
        self.pushButton.clicked.connect(lambda: self.update_profile())
        self.pushButton_2.clicked.connect(lambda: self.update_balance())

    def retranslateUi(self, mng_window):
        _translate = QtCore.QCoreApplication.translate
        mng_window.setWindowTitle(_translate("mng_window", "User Profile"))
        self.label.setText(_translate("mng_window", "User Management"))
        self.label_2.setText(_translate("mng_window", "Email"))
        self.label_3.setText(_translate("mng_window", "Password"))
        self.label_4.setText(_translate("mng_window", "Edit Details"))
        self.label_5.setText(_translate("mng_window", "Add Balance"))
        self.label_6.setText(_translate("mng_window", "Card Number"))
        self.label_7.setText(_translate("mng_window", "CVV"))
        self.label_8.setText(_translate("mng_window", "Amount"))
        self.pushButton.setText(_translate("mng_window", "Update"))
        self.pushButton_2.setText(_translate("mng_window", "Recharge"))
        self.label_9.setText(_translate("mng_window", "**- Click the X sign to close this window"))

    def load_data(self):
        self.textEdit.setText(self.mail)
        self.textEdit_2.setText(self.passw)

    def update_profile(self):
        em = str(self.textEdit.toPlainText())
        pasw = str(self.textEdit_2.toPlainText())
        if em == "" or pasw == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Fields Cannot be Empty!!")
            msg.setWindowTitle("Error!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        else:
            query = f"Update user_list set email='{em}', password='{pasw}' where username='{self.uname}';"
            c.execute(query)
            conn.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Profile Updated Successfully!!")
            msg.setWindowTitle("Updated!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()

    def update_balance(self):
        cc = str(self.textEdit_5.toPlainText())
        cvv = str(self.textEdit_3.toPlainText())
        added_balance = int(self.textEdit_4.toPlainText())
        if cc == "" or cvv == "" or str(added_balance) == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Fields Cannot be Empty!!")
            msg.setWindowTitle("Transaction Failed!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()
        else:
            initial_balance = int(self.bal)
            initial_balance += added_balance
            query = f"update user_list set deposit='{initial_balance}' where username='{self.uname}';"
            c.execute(query)
            conn.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Balance Successfully Added to Your Account!!")
            msg.setWindowTitle("Transaction Completed!")
            msg.setStandardButtons(QMessageBox.Ok)
            msg.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mng_window = QtWidgets.QMainWindow()
    ui = Ui_mng_window()
    ui.setupUi(mng_window)
    mng_window.show()
    sys.exit(app.exec_())
